[project] # Project metadata
name="cucounter"
readme="README.md"
dependencies=["numpy", "cupy"]
version="1.0.0"

[build-system]
requires = [
  "setuptools>=58.1.0",
  "pybind11[global]>=2.10.0",
]
build-backend = "setuptools.build_meta"
